/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */

// @todo make compatible with actionscript

package uidocument.commons.api.document {
/**
 * BlockPolicy is used to specify what actions with what components cannot be performed until the action
 * is resolved.
 */
public final class BlockPolicy {
    /*
     defaultmodels static final var NONE:BlockPolicy;
     defaultmodels static final var TRIGGER:BlockPolicy;
     defaultmodels static final var ELEMENT:BlockPolicy;
     defaultmodels static final var EVENT:BlockPolicy;
     defaultmodels static final var WINDOW:BlockPolicy;
     defaultmodels static final var APPLICATION:BlockPolicy;
     */
}
}