/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */
/*
 * Copyright (c) 2008, Vaclav Slovacek. All Rights Reserved.
 *
 * Product: UIProtocol Java
 *
 * This source-code is released under following license:
 * - no release outside i2home project is allowed
 * - this copyright notice must be placed unmodified in every file derived from this source code
 */

// @todo make implement resolved described
package uidocument.commons.api.document {

public class Event {

    private var id:String;

    public function Event() {
        this.id = null;
    }
    
    /**
     * Retrieves stamp assigned to the event if any.
     *
     * @return stamp assigned to the event if any, otherwise null
     */
    public function getStamp():String {
        return null;
    }

    /**
     * Retrieves time when the event occurred.
     *
     * @return time when the event occurred.
     */
    public function getTime():Number {
        return 0;
    }

    /**
     * Sets stamp used for the component.
     *
     * @param stamp used for the component
     */
    public function setStamp(stamp:String):void {

    }

    public function getId():String {
        return this.id;
    }

    public function setId(id:String):void {
        this.id = id;
    }

}
}
