/* Automatically generated by IntelliJ IDEA from Java, revision needed before production use */


package uidocument.commons.api.document {
public class MultiClass {

    function getClasses():Array {
        return null;
    }

    ;

    function setClasses(classes:Array):void {

    }

    ;
}
}
